/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'md3-primary': '#6750A4',
        'md3-on-primary': '#FFFFFF',
        'md3-primary-container': '#EADDFF',
        'md3-on-primary-container': '#21005D',
        'md3-secondary': '#625B71',
        'md3-on-secondary': '#FFFFFF',
        'md3-secondary-container': '#E8DEF8',
        'md3-on-secondary-container': '#1D192B',
        'md3-tertiary': '#7D5260',
        'md3-on-tertiary': '#FFFFFF',
        'md3-tertiary-container': '#FFD8E4',
        'md3-on-tertiary-container': '#31111D',
        'md3-error': '#B3261E',
        'md3-on-error': '#FFFFFF',
        'md3-error-container': '#F9DEDC',
        'md3-on-error-container': '#410E0B',
        'md3-background': '#FFFBFE',
        'md3-on-background': '#1C1B1F',
        'md3-surface': '#FFFBFE',
        'md3-on-surface': '#1C1B1F',
        'md3-surface-variant': '#E7E0EC',
        'md3-on-surface-variant': '#49454F',
        'md3-outline': '#79747E',
        'md3-outline-variant': '#CAC4D0',
        'md3-shadow': '#000000',
        'md3-scrim': '#000000',
        'md3-inverse-surface': '#313033',
        'md3-inverse-on-surface': '#F4EFF4',
        'md3-inverse-primary': '#D0BCFF',
      },
      borderRadius: {
        'md3-none': '0px',
        'md3-small': '8px',
        'md3-medium': '12px',
        'md3-large': '16px',
        'md3-extra-large': '28px',
        'md3-full': '9999px',
      },
      boxShadow: {
        'md3-level1': '0 1px 2px rgba(0,0,0,0.3), 0 1px 3px 1px rgba(0,0,0,0.15)',
        'md3-level2': '0 1px 2px rgba(0,0,0,0.3), 0 2px 6px 2px rgba(0,0,0,0.15)',
        'md3-level3': '0 4px 8px 3px rgba(0,0,0,0.15), 0 1px 3px rgba(0,0,0,0.3)',
        'md3-level4': '0 6px 10px 4px rgba(0,0,0,0.15), 0 2px 3px rgba(0,0,0,0.3)',
        'md3-level5': '0 8px 12px 6px rgba(0,0,0,0.15), 0 4px 4px rgba(0,0,0,0.3)',
      },
      fontFamily: {
        'md3-display': ['Noto Sans SC', 'Roboto', 'sans-serif'],
        'md3-headline': ['Noto Sans SC', 'Roboto', 'sans-serif'],
        'md3-title': ['Noto Sans SC', 'Roboto', 'sans-serif'],
        'md3-body': ['Noto Sans SC', 'Roboto', 'sans-serif'],
        'md3-label': ['Noto Sans SC', 'Roboto', 'sans-serif'],
      },
      transitionTimingFunction: {
        'md3-standard': 'cubic-bezier(0.2, 0, 0, 1)',
        'md3-decelerate': 'cubic-bezier(0, 0, 0, 1)',
        'md3-accelerate': 'cubic-bezier(0.3, 0, 1, 1)',
        'md3-emphasized': 'cubic-bezier(0.2, 0, 0, 1)',
      },
      animation: {
        'md3-fade-in': 'md3FadeIn 300ms cubic-bezier(0, 0, 0.2, 1)',
        'md3-slide-up': 'md3SlideUp 300ms cubic-bezier(0, 0, 0.2, 1)',
        'md3-scale-in': 'md3ScaleIn 200ms cubic-bezier(0, 0, 0.2, 1)',
      },
      keyframes: {
        md3FadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        md3SlideUp: {
          '0%': { transform: 'translateY(100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        md3ScaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
